<?php

/**
 * Implements hook_views_api().
 */
function views_message_views_api() {
  return array(
    'api' => '3',
    'path' => drupal_get_path('module', 'views_message'),
  );
}

/**
 * Implements hook_theme().
 */
function views_message_theme() {
  return array(
    'views_message_container' => array(
      'variables' => array(
        'type' => NULL,
        'class' => NULL,
        'message' => NULL,
      ),
    ),
  );
}

/**
 * Themes a message container.
 *
 * @param array $variables
 *   Includes the 'type', 'class' and 'message' variables.
 */
function theme_views_message_container($variables) {
  return '<div class="messages views-message ' . $variables['type'] . $variables['class'] . '">' . $variables['message'] . '</div>';
}
